name: Validate example API swagger documentation
on: [push, pull_request]
jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use local action
      id: example
      uses: ./swagger-validator-2
      with:
        files: |
          swagger-validator-2/example.openapi.yaml
    - name: Output export variable
      run: |
        echo ${{ steps.example.outputs.validFiles }}
        echo ${{ steps.example.outputs.invalidFiles }}
